// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtOeGLVxMX2p9dI_08yuSNkBkc4eM-csU',
    appId: '1:373826412993:web:c2d26cffdc9555349c8f40',
    messagingSenderId: '373826412993',
    projectId: 'notes-app-8c55e',
    authDomain: 'notes-app-8c55e.firebaseapp.com',
    storageBucket: 'notes-app-8c55e.appspot.com',
    measurementId: 'G-NP7XTNPXW5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn9mfPo5Cqolpq2xedfvbZi8kBCdhkiPk',
    appId: '1:373826412993:android:87c41c0de058b9499c8f40',
    messagingSenderId: '373826412993',
    projectId: 'notes-app-8c55e',
    storageBucket: 'notes-app-8c55e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMjzt_gISXy60gqrKdnNy6ZloXoDCrg8c',
    appId: '1:373826412993:ios:065e49b33dc2a8749c8f40',
    messagingSenderId: '373826412993',
    projectId: 'notes-app-8c55e',
    storageBucket: 'notes-app-8c55e.appspot.com',
    iosClientId: '373826412993-m7bnisli08i0be8908aj1346ujhn7lpo.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMjzt_gISXy60gqrKdnNy6ZloXoDCrg8c',
    appId: '1:373826412993:ios:065e49b33dc2a8749c8f40',
    messagingSenderId: '373826412993',
    projectId: 'notes-app-8c55e',
    storageBucket: 'notes-app-8c55e.appspot.com',
    iosClientId: '373826412993-m7bnisli08i0be8908aj1346ujhn7lpo.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesApp',
  );
}
